export const images = {
  camera: require('../../assets/Images/camera.png'),
  gallery: require('../../assets/Images/gallery.png'),
  cross: require('../../assets/Images/cross.png'),
  upload: require('../../assets/Images/upload.png'),
  warning: require('../../assets/Images/warning.png'),
  check: require('../../assets/Images/check.png'),
  edit: require('../../assets/Images/edit.png'),
  delete: require('../../assets/Images/delete.png'),
  add: require('../../assets/Images/add.png'),
  close: require('../../assets/Images/multiply.png'),
  arrowup: require('../../assets/Images/arrowup.png'),
  arrowdown: require('../../assets/Images/arrowdown.png'),
  file: require('../../assets/Images/file.png'),
  user: require('../../assets/Images/user.png'),
  dashboard: require('../../assets/Images/dashboard.png'),
  notification: require('../../assets/Images/notification.png'),
  document: require('../../assets/Images/document.png'),
  userFocused: require('../../assets/Images/userFocused.png'),
  dashboardFocused: require('../../assets/Images/dashboardFocused.png'),
  notificationFocused: require('../../assets/Images/notificationFocused.png'),
  documentFocused: require('../../assets/Images/documentFocused.png'),
  location: require('../../assets/Images/location-pin.png'),
  call: require('../../assets/Images/call.png'),
  mark: require('../../assets/Images/mark.png'),


};
